db:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
    ports:
       - 4306:3306
    volumes:
        - //Users/{userName}/php_sample/db/datadir:/var/lib/mysql
web:
    image: test/php:5.6.23-apache
    volumes:
        - /Users/{userName}/php_sample:/var/www/html
    links:
        - db:mysql
    ports:
        - 8080:80