db:
    build: ./environment/db/
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: app
        TZ: "Asia/Tokyo"
    ports:
       - 4306:3306
    volumes:
        - ./environment/db/volume/:/var/lib/mysql
web:
    build: ./environment/php/
    volumes:
        - ./app:/var/www/html
    links:
        - db
    ports:
        - 8888:80